source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftSignatureView_Example', :exclusive => true do
  pod "SwiftSignatureView", :path => "../"
end

target 'SwiftSignatureView_Tests', :exclusive => true do
  pod "SwiftSignatureView", :path => "../"

  
end
