source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftSignatureView_Example' do
  pod "SwiftSignatureView", :path => "../"
end

target 'SwiftSignatureView_Tests' do
  pod "SwiftSignatureView", :path => "../"
end

